### PR TITLE
New blade with prices for product

### PR DESCRIPTION
**Pull request by megafreeman**

### CODE REVIEW

**Comment by megafreeman** [comment]
@asvishnyakov Alexander, could you make code review please

**Comment by asvishnyakov** [comment]
1. User must not be able to add multiple prices with the same number of min. quantity
2. You must check 'delete' permission on price deletion (look at api controller) and 'pricing:read' in item-prices.tpl.html
3. (note sure, @tatarincev confirm please) api/products/{productId}/{catalogId}/pricesWidget → api/catalog/{catalogId}/products/{productId}/prices or api/pricing/{catalogId}/{productId}/prices
4. You must not loading catalogs manually. Pricelists has assignments which bind pricelists and catalogs.
5. Do not use inline styles

**Comment by megafreeman** [comment]
1, 2 and 4 items from code review were implemented in last commits. 3rd item not applicable for this task i suppose

**Comment by megafreeman** [comment]
1, 2 and 4 items from code review were implemented in last commits. 3rd item not applicable for this task i suppose

**Comment by megafreeman** [comment]
I updated Pricing module on [demo-vc](http://demovc-admin-dev.azurewebsites.net) to preview changes.
image

**Comment by Woland2k** [comment]
Done incorrectly, there shouldn't be a drop down for pricing. There should be "Add Price" button in the toolbar and no pricelist dropdown. Look at the description of 3 cases given in https://github.com/VirtoCommerce/vc-platform/issues/1115

**Comment by megafreeman** [comment]
Another batch of the changes is available on the [demo-vc](http://demovc-admin-dev.azurewebsites.net) for preview:
1. fix validation data in grid
2. display name of currency in price list selector
3. empty (N/A) initial list price instead 0

image

**Pull request merged**
